[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "16"

[build]
  publish = "docs/.vitepress/dist"
  command = "npx pnpm@7.27.1 i --store=node_modules/.pnpm-store && pnpm -w run deploy"

[functions]
  node_bundler = "esbuild"
