name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.4.0

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Install Tsup
        run: pnpm install -g tsup
      
      - name: Rush 
        run: pnpm install -g @microsoft/rush@5.50.0
       
      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
      
      - name: Rush Build
        run: rush build
      
      - name: Publish to NPM
        run: pnpm -r publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
