name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.4.0
      
      - name: Write mongo-api secrets to .env file
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          DATASOURCE: ${{ secrets.DATASOURCE }}
          DATABASE: ${{ secrets.DATABASE }}
          COLLECTION: ${{ secrets.COLLECTION }}

        run: |
          echo "API_KEY=${API_KEY}" >> .env
          echo "API_BASE_URL=${API_BASE_URL}" >> .env
          echo "DATASOURCE=${DATASOURCE}" >> .env
          echo "DATABASE=${DATABASE}" >> .env
          echo "COLLECTION=${COLLECTION}" >> .env

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Install Unbuild
        run: pnpm install -g unbuild
      
      - name: Rush 
        run: pnpm install -g @microsoft/rush@5.50.0
       
      - name: Rush Install
        run: rush update
      
      - name: Rush Build
        run: rush build
      
      - name: Publish to NPM
        run: pnpm -r publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
